name: Sync Charmstore Credentials

on: 
  workflow_dispatch:
    inputs:
      DRY_RUN:
        description: 'true/false whether to run action in dry-run mode'
        required: true
        default: 'true'

jobs:
  sync_charmstore_credentials:
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.5.0
        with:
          SECRETS: |
            ^CHARMSTORE_CREDENTIAL_DEBUG$
          REPOSITORIES: |
            ^canonical/argo-operators$
          DRY_RUN: ${{ github.event.inputs.DRY_RUN }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          CONCURRENCY: 10
        env:
          CHARMSTORE_CREDENTIAL_DEBUG: ${{ github.event.inputs.CHARMSTORE_CREDENTIAL }}
